# -*- coding: utf-8 -*-
"""next word predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gsa42kOjvKegzW23aSZydnQAn39XPUjT
"""

text = """Hey Radhika! Kaisi ho?
Hey Rohan, main bilkul thik hun. Tu bata, kaisa hai?
I'm good too, yaar. Tumne suna ki next week school wali trip hai?
Haan, mujhe toh pata chal gaya hai. Itna excited hun mai! Tu bhi aa raha hai na?
Bilkul, Radhika. Ek trip miss karunga toh behad boring ho jayega. Hum kaha ja rahe hai?
Humare college ne Goa ka plan banaya hai. Wahin par enjoy karne wale hai, khub saare beaches aur parties.
Wow, Goa is the best! Mere friends ne bhi wahi trip ki hai. Wahan ke beaches aur night life legendary hai, aur I can't wait to experience it with you.
Awww, that's so sweet of you, Rohan. Hum jarur masti karenge. Tere friends ke sath bhi aayenge?
Haan, mere do close friends aur unke girlfriends bhi aa rahe hai. Par woh toh sirf dost hai, main toh tumhare sath hi time spend karna chahta hun.
Waise, tu aur teri dosti ki kahani sunao na. Kabse friends ho?
Hum bachpan se hi friends hai. Saath me school bhi kiya hai aur har choti badi baat share karte hai. Ek saath trip par jana dream come true hai!
Uff, Rohan, tum toh bohot cute ho. We are going to have an amazing time together, I can sense it already.
Haan, Radhika. Aur tere dosti ka bhi ek story sunao na. Kuch interesting hai?
Haha, meri life ka sabse interesting moment tha jab maine dance competition jeeta. Wahan par ek stranger mujhe motivate kiya tha, aur uss din se hamari dosti shuru ho gayi.
Wah! Dance competition jeetna koi aam baat nahi hai. Aur uss stranger ko ab tak yaad hai?
Haan, yaar. Uske sath ab tak touch me rehte hai. Next competition ke liye bhi prepare kar rahe hai. Uss din tera support chahiye hoga.
Bilkul, Radhika. Tere liye main hamesha ready hun. Aur teri dance ki practice hum trip pe bhi kar sakte hai.
Sach? Tu toh best dost nikla, Rohan. Agar teri wajah se main trophy jeeti toh hum dono celebrate karenge.
Haan, bilkul celebrate karenge. Aur agar tu trophy jeeti toh, mujhe ek romantic dance date par le jaogi, deal?
Deal, Rohan! Waise, mujhe tere romantic side pe bharosa nahi tha. Suprise hua, mujhe pasand aaya.
Vo toh bas shuruat hai, Radhika. I can't wait to create more memories with you on this trip. Tu jaanti hai, hume best jodi wala award bhi milega.
Aww, tu bhi na. Hum sach me best jodi hai. I'm so lucky to have you, Rohan.
I'm the lucky one, Radhika. Chal, ab trip ka wait karna band karte hai aur humari romantic moments ki planning karte hai.
Aayush, kya haal hai? Bade tension ke saath dikh rahe ho aaj kal.
Riya, tu bilkul sahi keh rahi hai. Office ka kaam aur ghar ke pressure sab handle nahi ho raha.
Tension lene ki kya zaroorat hai? Hamesha baat kar liya karo, dost log support karenge.
Mujhe kabhi samajh nahi aata ki logon se madad maang lein. Thoda ego aa jata hai.
Aayush, samajhne ki koshish karo. Dost hain, issliye madad karne mein khushi milengi unhe. Apne ego ko side kar do na, please?
Theek hai, Riya. Main bhi koshish karunga. Lekin kabhi kabhi dil bahut heavy ho jata hai.
Aayush, humara stress level control karna bahut zaroori hai. Maine ek nayi technique try ki hai - meditation. Tere liye bhi beneficial ho sakti hai.
Meditation? Mujhe toh laga sirf babaji aur sadhu log karte hain.
Nahi, aaj ke generation mein bhi log kar rahe hain. Mental health ko improve karne mein kaafi help karta hai.
Accha hai toh ek baar try karunga. Tu bhi meri meditation partner banegi?
Zaroor! Hum milkar shuru karte hain. Aur yaad rakh, humein stress ko control karne ke liye positive environment ki zaroorat hoti hai.
Woh toh samajh gaya, lekin kabhi kabhi kuch baattein share karne ka dar lagta hai.
Aayush, humein apne feelings aur thoughts share karne mein darr nahi hona chahiye. Main hamesha tere saath hu.
Riya, tujhse baat karne se kitni energy milti hai, yaar! Tu mere stress ko door kar deti hai.
Yeh toh sirf shuruaat hai, Aayush. Abhi toh bahut kuch baaki hai humare beech.
Kya matlab hai tumhara?
Matlab hai, hum saath saath iss stress ki fight karenge. Tere saath reh kar, tujhe zaroor support karungi.
Riya, tu sach mein amazing hai. Tujhse mil ke mujhe bahut achha laga.
Aayush, tu bhi bilkul kam nahi, ek bahut achhe insaan ho.
I'm really lucky to have you in my life, Riya.
Aayush, main bhi tujhse bahut pyaar karti hoon.
Riya, yeh toh unexpected tha. Par mujhe bhi tujhse pyaar ho gaya hai.
Aayush, aaj ke baad, hum saath stress ko face karenge aur pyaar se usse harayenge.
Ek saath khushi, pyaar aur support ke saath. I'm looking forward to it, Riya.
Me too, Aayush. Humara aage ka safar bahut achha hoga. Hum dono khubsurat pal banayenge.
Riya, tu sach mein meri zindagi mein chamak layi hai. I love you.
Aayush, I love you too. Tere bina meri zindagi adhuri hai.
Hey Anu, kya haal hai? Tune recently koi art, music ya dance class join ki hai?
Hey Aman! Haan, maine ek music class join kiya hai. Aur tu?
Awesome! Main bhi ek painting class mein hoon. Kitna fun hota hai na, alag alag art forms explore karne mein.
Bilkul! Music sikhna aur gaana gaana mujhe bohot khushi deta hai. Tumhe koi specific art form ya music instrument pasand hai?
Haan, mujhe guitar bohot pasand hai. Zor se strum karna aur soothing melodies banane ka maza hi kuch aur hai.
Mujhe piano bahut accha lagta hai. Ek hi saans mein saare octaves bajaana, wah! Bohot relaxing feel hoti hai.
Sach mein, piano ki taarifein khatam hi nahi hoti. Tum kabhi sikhna chahogi? Main teach kar sakta hoon.
Woh sab toh thik hai, par tujhe painting kaise lagti hai? Colors aur strokes se kaisa connection hai tere?
Painting mujhe inner peace aur self-expression deta hai. Har stroke ek kahaani sunata hai, colors ki boli hai woh.
Sounds so beautiful! Mujhe teri kuch paintings dekhni hai. Kya hum ek din art exhibition pe milke chal sakte hai?
Zaroor, ek art exhibition pe milna ek perfect idea hai. Wahan apni creativity ko share karke aur khush hokar.
Aman, tu bohot talented hai. Shayad tere saath time bitane se mujhe bhi kuch learn karne ko milega.
Tum bhi bohot creative ho, Anu. Main hamesha tere saath time bitana chahta hoon. Tum mere inspiration ho.
Aman, tune mere dil ko chu liya. Tere saath time bitane ki khwahish mere bhi dil mein hai.
Yeh sunke mere chehre pe muskurahat aa gayi hai. Mujhe lagta hai yeh pyaar ki shuruaat ho sakti hai.
Haan, shayad yeh humari love story ka pehla chapter hai. Art, music, aur dance ne hamari zindagiyan ek saath jod di hai.
Sach kahu toh, tere saath har ek pal ek alag art form ka anubhav lagta hai. Main hamesha tere saath rehna chahta hoon.
Aman, hamesha mere saath rehna. Tum mere art ka muse ho, mera dil ki dharkano ka raag ho.
Anu, tum meri zindagi ki masterpiece ho. Tumse pyaar karna mere liye bahut natural hai.
Aman, main bhi tumse bahut pyaar karti hoon. Tum ho meri kala ka saath, meri zindagi ka rang.
Arey, Deepika! Suno, aaj maine ek amazing app discover kiya hai. It's called Todoist!
Oh, really? Todoist kaisa hai, Rishi?
Deepika, Todoist ek task management app hai. It helps you stay organized and focused on work. Tum tasks create kar sakti ho and set reminders to keep track of everything.
Wah, Rishi! Yeh toh bahut useful hai. Abhi mujhe exam preparation ke liye ek acha app chahiye.
Haan, exam time pe Forest app bhi bohot useful hai. It helps you stay away from distractions. Jab tum padhna shuru karti ho, trees plant ho jate hai and if you use your phone, your virtual tree dies, yani exam me accha perform nahi kar paoge.
Accha idea hai, Rishi! Tree plant karne ka motivation hoga mujhe. Aur productivity ke liye, koi aur app recommend kar sakte ho?
Zaroor, Deepika! Trello bhi ek acchi option hai. Trello ke through, you can create boards, lists, and cards to organize your tasks. Tum apne assignments, notes, aur deadlines sab ek jagah pe manage kar sakti ho.
Thank you, Rishi! Tumne bahut helpful apps share kiye. Ab mujhe bhi kuch recommend karna hai.
Zaroor, Deepika! Mere liye kaun sa app useful tha?
Rishi, Mendeley ek best app hai research papers aur articles ke liye. It helps you organize and cite your sources. Bahut useful hai college projects me.
Wow, Deepika! Tum kitni informative ho. Ab mujhe bhi Mendeley try karna chaiye.
Haan, Rishi. Bahut useful hai. By the way, humara conversation kitna interesting ho raha hai, na?
Haan, Deepika. Tumhari knowledge aur suggestions ne meri interest badha di hai. Aur tumhari saath bhi bahut achhi feeling aa rahi hai.
Rishi, mujhe bhi aisa lag raha hai. Tum bahut caring aur thoughtful ho. Mujhe lagta hai hum bahut achhe friends ban sakte hai.
Haan, Deepika. Lekin mujhe ek baat poochni hai. Kya tum mere saath date pe chalogi?
Rishi, mujhe bahut acha lagega. Main bhi tumse bahut time spend karna chahti hoon.
Sach, Deepika? Yeh toh amazing news hai. Abhi mujhe aur zyada excite hone ki zaroorat hai!
Rishi, yeh sirf shuruat hai. Humare saath bahut khoobsurat pal hai hamesha ke liye.
Haan, Deepika. I can't wait for our first date. Yeh apps ke discussion se kuch aur zyada khoobsurat chize shuru ho rahi hai humare beech.
Absolutely, Rishi. Ek simple topic se humari friendship aur connection itni deep ho gayi hai. I'm really looking forward to our date too.
Abhi se main date ke sapne dekhne laga hoon, Deepika. Aur I promise, humari date bhi productive hogi, just like the apps we discussed.
Haha, Rishi! You always manage to make me smile. I'm sure our date will be special and unforgettable.
Hey Priya! Lag raha hai ki tumhe street foods ki bahut yaad aa rahi hogi. Kaisa laga India ke galiyon ki khushboo aur taste?
Hey Rahul! Bilkul sahi kaha tumne. India ke street foods ka taste phir se yaad aa gaya. Waise tumhara favourite street food kaunsa hai?
Abhi tak toh Mumbai ke vada pav aur pav bhaji se zyada kuch nahi mila hai mujhe. Vada pav ka toh swaad hi alag hota hai, spicy chutney ke saath.
Haan, Mumbai ke vada pav ko koi takkar nahi de sakta. Lekin Delhi mein kele ke chips aur golgappe bhi ek dum bomb hote hai. Unki meethi chutney hi kya kehne!
Delhi ke golgappe toh baat hi alag hai. Woh ek golgappa khaane ke baad zubaan ko space hi nahi dete. Aur aapka toh favourite street food kaunsa hai?
Mera favourite toh Ahmedabad ke khaman dhokle hai. Unki spongy texture aur teekhe tadke ne mujhe unki deewani bana diya hai. Ek bite lete hi dil khush ho jaata hai.
Wow, Ahmedabad ke khaman dhokle ke baare mein toh kafi suna hai. Agar kabhi waha jaao, toh zaroor try karunga. Par abhi romantic moment banaye, kya tum mujhe khaman dhokle try karake khush karogi?
Haha, zaroor Rahul! Agar tum Ahmedabad aao, toh main khud hi tumhe khaman dhokle khilungi. Waise bhi mujhe koi excuse chahiye tujhse milne ka.
Awww Priya, tum bhi na. Tumhe dekhne ke liye mai kahin bhi aa jaunga. Aur waha khaman dhokle ke saath thodi dooriyan bhi kam ho jaayengi, what say?
Haan Rahul, bilkul. Mai bhi hamesha tere saath rehna chahti hu. Tum mere dil ki dharti pe khaman dhokle ki tarah bas gaye ho.
Priya, tumhara pyaar toh mere dil ko bhi chhu gaya hai. Tum hai meri life ka special ingredient, jiske bina mere din adhoore hote hai. I love you!
Rahul, tumhara pyaar aur mera dil bhi sirf tumhare liye dhadakta hai. I love you too!
Hey Ria! Kya haal hai? Literature ke baare mein kuch baat kar sakte hain?
Hey Aman! Haan, bilkul! Mujhe bhi regional literature bahut pasand hai. Tumne koi favorite author ya book padhi hai?
Haan, mein recently Chetan Bhagat ki 'Half Girlfriend' padhi thi. Magar mujhe lagta hai ki hume apne regional authors ko bhi support karna chahiye. Tum padti ho kisi regional writer ki book?
Haan, meine Ekta Kapoor ki 'Blockbuster Tales of Bollywood' padhi hai aur woh mujhe bahut pasand aayi. Bollywood ke regional movies ke baare mein unki representation bahut achhi hai.
Ekta Kapoor ki books bhi hai? Interesting! Lekin kya tumhe lagta hai ki regional literature Hindi literature ka hissa hai ya alag hai?
Mujhe lagta hai ki regional literature Hindi literature ka jaroori hissa hai. Isse humare desh ki rich cultural diversity aur vernacular languages ka samman hota hai. Regional literature Hindi literature ko aur bhi majboot banati hai.
Tum bilkul sahi keh rahi ho, Ria. Aur regional literature mein kuch aise topics hai jo Hindi literature mein shayad kam dikhayi dete hai. Isse readers ko aur alag perspective milta hai.
Haan, bilkul! Regional literature mein humae alag-different cultures, traditions aur emotions ka pata chalta hai. Yeh stories aur characters hume ekdum real lagte hai.
Sach mein! Aur aise authors ko encourage karna chahiye, taaki unki alag-alag stories aur perspectives hum tak pahunche.
Bilkul, Aman! Yahan tak ki hum khud bhi likh sakte hain regional literature ke upar. Kya tumne kabhi socha hai kisi regional writer ki tarah ek book likhne ki?
Well, abhi tak nahi socha tha, par tere kahne pe mujhe bhi idea aa raha hai. Shayad ek story likhun jisme kisi regional language aur culture ka use ho.
Wow, that sounds fascinating! Tumhari story zaroor padhungi. Aur kya kya experiences aur challenges hai regional writers ke?
Regional writers ko apni language aur culture ke saath connect rehna padta hai. Unhe apne readers ko samajhne mein thoda time lagta hai, lekin jab woh connection ban jata hai, toh kuch khaas hi hota hai.
Wah, yeh bahut inspiring hai! Mujhe lag raha hai ab regional literature ko aur deeply explore karna chahiye.
Absolutely! Main bhi apna knowledge expand karna chahta hoon. Maybe hum ek dusre ko suggest kar sakte hain kuch regional books?
Haan, zaroor! Main 'Godan' by Munshi Premchand suggest karti hoon. Yeh Hindi literature ka ek classical masterpiece hai.
Aur main 'Randamoozham' by M.T. Vasudevan Nair suggest karunga. Yeh Malayalam literature ka ek popular epic hai.
Sounds interesting! Hum ek dusre ko regional literature discover karne mein help karenge. Tumhe agar kabhi koi conflicted situation ho, toh mujhse zaroor share karna.
Oh, don't worry, Ria. Tumhare personal emotions ko appreciate karne ke liye main hamesha yahan rahunga.
Thank you, Aman. Tumhari friendship ki value mujhe bahut hai.
You're welcome, Ria. Tumhare saath time spend karna, baat karna, yeh sab mujhe bahut khushi deti hai.
Mujhe bhi bahut achha lag raha hai, Aman. Tumhari company ke saath kuch magical sa lagta hai.
Ria, I think we have a great connection. Tum mujhe bahut pasand ho.
Aman, even I feel the same way. Tum mere liye special ho.
Ria, kya tum mere saath ek coffee date pe chalogi?
Aman, mujhe bahut khushi hogi! Main zaroor chalungi.
Hey Simran! Kaisi ho? I was just thinking, Bollywood ne humare desh ka culture aur pop culture mein kitna influence daala hai. Kya tumhe lagta hai?
Hey Rohan! Main theek hun, tum batao? Haan, Bollywood ka influence bahut zyada hai! Woh humari zindagi mein itna present hai ki koi bhi Indian pop culture ki baat kare, Bollywood ka mention toh hona hi chahiye.
Haan yaar, bilkul sahi keh rahi ho. Bollywood ke gaane, dialogues, fashion sab kuch logon ko inspire karte hai. Har wedding par toh Bollywood songs hi bajte hai!
Sach mein! Aur Bollywood actors ki styling aur outfits bhi logon ko bahut pasand aate hai. Unki dressing sense dekhkar hum bhi fashion trends follow karte hai.
Absolutely! Aur kya kehna, Bollywood movies ke dialogues toh viral ho jaate hai. Kuch dialogues toh itne famous hote hai ki log unhe roz bolte hai aur memes bana dete hai!
Haha, bilkul! Woh "Mere Karan-Arjun aayenge" wala dialogue ya phir "Jab tak hai jaan, main nachungi" dialogue, kitne logon ne apne daily conversations mein use kiye hai. Yeh sab Bollywood ka impact hai.
Sahi pakde hain! Aur Bollywood movies ke romantic moments ko dekhkar, kitne log apne relationships mein filmy touch dete hai. Kuch log toh proposal bhi Bollywood style mein karte hai.
Haan yaar, dekhte hi dekhte unka pyaar aur romance bhi Bollywood movies jaisa ho jaata hai. Yeh movies logon ko aspiration aur inspiration deti hai apne relationships mein bhi.
Absolutely, Bollywood has become an integral part of our lives and pop culture. But you know what? Tujhe dekhkar mujhe bhi woh Bollywood wali feeling aa rahi hai.
Aww, thank you, Rohan! Tum bhi bilkul Bollywood hero ki tarah romantic lines bol rahe ho.
Haha, tumhare saath time spend karke mujhe bhi filmi banata hai. Tum dil se itni khoobsurat ho, jaise koi Bollywood actress!
Stop it, you're making me blush. Tum bhi kuch kam nahi ho, Rohan. Tumhare saath time bitane se mujhe bhi filmy moments milte hai.
Toh kya hum ek aur filmy moment create kar sakte hai? Simran, tum meri girlfriend banogi?
Rohan, mujhe bahut khushi hogi, main tumhari girlfriend banungi!
Riya: Hi Raj, aaj kal sabke peeche ek naya chakkar hai - 'Keto Diet.' Tumne is bare me suna hai?
Haan, Riya! Ye toh badi popular ho gayi hai. Carbs kam karke body ko fat burn karne ki koshish hoti hai.
Haan, mujhe bhi pata chala ki isme high fat foods like butter aur oils ka istemal hota hai. Lekin mujhe ye samajh nahi aata ki body ko itna fat khaane se weight kam kaise hoga.
Woh isliye Riya kyunki jab hum achhe fats consume karte hain, toh body ko energy ke liye carbs ki jagah fat burn karna padta hai. Aur isse weight kam hota hai.
Oh, samajh me aaya. Lekin mujhe yeh diet practical nahi lagti hai. Mai toh sirf healthy food khati hu aur exercise karti hu.
Tum sahi keh rahi ho. Zaruri hai ki hum ek balanced diet lein aur regular exercise karein. Agar sirf diet pe concentrate karein toh body mein weakness aa sakti hai.
Aur kya karte ho gym mein Raj? Koi specific routine hai ya bas mann kiya woh kar lete ho?
Nahi yaar, mujhe ek trainer ne workout schedule banaya hai. Woh haddi-muscle exercises, cardio aur stretching ka mix hai.
Mujhe bhi gym join karna chahiye. Abhi tak toh ghar pe hi exercise karti thi. Tumhara motivation mujhe bhi chahiye.
Definitely, Riya! Mai tumhara workout partner ban sakta hu aur motivation bhi provide karunga.
Thanks, Raj! Yehi toh mujhe tum me sabse accha lagta hai. Tum healthy lifestyle ko seriously lete ho.
Woh toh tumhari wajah se hai, Riya. Tum fit and active rehne ki wajah se mujhe bhi inspire karti ho.
Awww, sachme? Thank you, Raj!
Haan, Riya. Tumhare saath gym jaane ka idea mujhe acha lag raha hai. Aur kya kahoge?
Raj, tum bahut sweet ho. Haan, mai bhi aaj se gym join karti hu. Hum saath me fit rahenge!
Hey Rohit, kaisa hai? I heard you have completed your 12th boards. Congrats!
Hey Riya! Haan yaar, finally done with boards. Thank you! Tera bhi boards khatam ho gaye kya?
Haan, abhi thode din pehle hi huye. So, what are your plans now? Which college are you aiming for?
Well, I am considering both engineering and medical streams. Confused hoon yaar. Tujhe kya lagta hai?
Hmm, tough choice indeed. I'm more inclined towards engineering. I have always been interested in technology and computers.
That's great! Maybe hum ek hi college me admission le sakte hai. We can pursue our dreams together, what say?
Sounds like a plan! Itna time saath bitane ka mauka milega and we can help each other out too.
Absolutely! Koi problem nahi hoga agar hum different streams ke courses lete hai, right?
Of course not! Stream toh alag hai, but dosti aur support toh same rahega. Ek doosre ki madad karte rahenge.
True, dosti kabhi depend nahi karti hai career choices pe. By the way, koi specific college in mind for engineering?
Well, I am really interested in getting into the Indian Institute of Technology . It's one of the best engineering colleges in India. What about you?
Even IIT is my dream college, Riya! But competition vahaan bahut tough hai. Hopefully, hum dono milke usme admission le paayege.
Absolutely! Together, we can achieve anything. Imagine the fun we will have while studying and exploring the campus together.
Haan yaar, I can't wait for college life. It will be amazing to have you around. Aur tu jaanti hai, mujhe tere saath time spend karne me bahut mazaa aata hai.
Aww, that's really sweet of you, Rohit. Mujhe bhi tere saath time spend karke bahut khushi milti hai. I'm glad we have similar career aspirations.
Riya, main tujhse ek baat share karna chahta hoon. Tumse milne se pehle, mera confidence bohot low tha. Tumne life me positive changes laya hai.
Sach? I'm glad I could make a difference in your life, Rohit. Tum bhi mere liye special ho, and I am grateful to have you as a friend.
Riya, dosti ke saath ab ek aur cheez bhi jodni hai. I really like you, Riya. Will you be my girlfriend?
Rohit, I had a feeling you might say that. Tum bhi mere liye khaas ho and I have feelings for you too. Yes, I will be your girlfriend.
That's amazing, Riya! I'm the luckiest guy to have you in my life. Ab college ke saath saath pyaar bhi badh jayega, what say?
Absolutely, Rohit! Our college journey will be filled with love and support. Can't wait to create wonderful memories together.
Hey Rishi, have you watched any Rajnikanth movie lately?
Oh, definitely! Rajnikanth is the king of style. His movies are always a rollercoaster ride.
I totally agree! But which one do you think is his best movie?
Well, for me, it has to be "Baasha". Rajnikanth's acting and dialogue delivery were at their peak in that film.
Really? I think "Sivaji: The Boss" is his best film. The storyline and his swag in that movie were unbeatable.
Oh, come on, Hina! "Chandramukhi" was fantastic as well. Rajnikanth's dual role as Vettaiyan and Saravanan was mind-blowing.
Yes, "Chandramukhi" was good too, but in my opinion, "Enthiran" was his masterpiece. The combination of science fiction and Rajnikanth's charisma was outstanding.
Well, I respect your opinion, but "Robo" couldn't surpass the magic of "Kabali". Rajnikanth's powerful performance as a don fighting for justice left a lasting impact.
You make a valid point, Rishi. "Kabali" was indeed a great film, but I still believe "Padayappa" is the best. The mass sequences and Rajnikanth's iconic punch dialogues were etched in our memories forever.
I can't deny that "Padayappa" had a strong impact, but "Muthu" was a game-changer. It went on to become the first Tamil film to achieve significant success in Japan. Rajnikanth's dancing skills were extraordinary in that movie.
Wow, I didn't know that! You always surprise me with your knowledge. But don't forget about "Sivaji: The Boss". Rajnikanth's style and punch dialogues were a rage among the audience.
Yes, I can't deny the style quotient of "Sivaji: The Boss". Rajnikanth's powerful screen presence and the fantastic visuals made it an unforgettable experience.
You always bring up great points, Rishi. That's why I enjoy our discussions.
Thank you, Hina. I enjoy our conversations too. You always have a unique perspective.
Oh, you're making me blush, Rishi.
Well, it's true. By the way, speaking of movies, would you like to go watch a Rajnikanth movie together sometime?
That sounds like a wonderful plan, Rishi. I would love to go on a movie date with you.
Great! Let's make it happen then. How about we catch the latest Rajnikanth movie this weekend?
Absolutely, Rishi! I'm really looking forward to it.
Me too, Hina. I can't wait for our movie date.
Hey, Kavya! Kab se online shopping karne lagi ho? Itna trend kaise badh gaya?
Hey, Rohan! Pata nahi, par ab toh sab kuch online milta hai. Itna convenient ho gaya hai shopping karna.
Haan, bilkul. Aur discount offers bhi itne tempting ho gaye hain. Sab kuchh sasta mil raha hai.
Sach mein! Aur delivery bhi itni fast ho gayi hai. Agar kuchh chahiye, ek click mein ghar tak pahuch jata hai.
Han, ab toh paas mein wala shop bhi compete nahi kar pata. E-commerce ne sabko impress kar diya hai.
Haan, aur woh bhi sirf ek app ke zariye. Ek phone mein sara bazaar pahuch gaya.
Aur, abhi toh lockdown hai. Bas, ghar pe baithe-baithe shopping kar sakte hain. Aur koi rishta nahi in online stores ka.
Haha! Sahi bola. Par offline stores jaane ka alag hi maza hai. Woh shopping ka feel kuch aur hi hota hai.
Haan, woh bhi hai. Par online shopping ki zaroorat bhi hain. Aur jab woh mujhe tere sath karne ki advice di, tab toh mujhe bhi samajh mein aa gaya ki e-commerce kitna important hai.
Awww, mujhse advice li? That's sweet, Rohan. Ek date par chal kar samajh lena, offline ya online, kya farak padta hai.
Tum itni cute ho, Kavya. Main toh tumhare sath kahi bhi jaa sakta hun, offline ya online.
Aw, thank you, Rohan. Tum bhi bilkul handsome ho. Hamesha mere saath khushiyon ka online store lagate ho.
Tumhari muskurahat dekh kar koi bhi surbhi chiz online nahi chaiye hoti.
Awww, Rohan! Tum bhi kuch nahi kam ho. Apne words se dil ko online kar dete ho.
Sach kahun toh, mujhe lagta hai hum dono offline, online, ya jaha bhi rahe, hamesha ek dusre ke liye bane hai.
Rohan, tum mere favorite shopping partner ban gaye ho, offline aur online dono mein.
Aur tum meri favorite shopping destination, jahaan mujhe har chiz mil jati hai – laughter, smiles, love, aur abhi toh ek date bhi.
Sach bolte ho, Rohan. I'm glad ki humari baat e-commerce se hui aur ab tak yahaan pahuch gayi.
Kavya, tum meri duniya ho. Aur iss duniya mein bahut saari romantic moments bhi jude hai.
Rohan, tum meri zindagi mein itni excitement laaye ho, ek romantic moment bhi zaroor judega.
Rohan: Hey, Riya! Tumne kabhi Indian folklore aur myths ke baare mein suna hai?
Haan, mujhe toh yeh topics bohot pasand hai! Ramayana aur Mahabharata jaise kisse mere dil ko chhoo jate hain. Tumhare paas koi favorite myth ya folklore hai?
 Haan, mere liye Krishna aur Radha ka prem katha sabse pyara hai! Unki pyari si raas leela aur bansuri ki dhun dil ko choo leti hai. Tum batao koi myth jo tumko bahut pasand hai?
Oh, mujhe Shiv aur Parvati ki paa raha hai! Unki prem kahani aur Ganga maiya se girti hui Ganga ka roop mere mann ko sukoon deta hai.
 Wah, Riya! Tum bahut deep thoughts rakhti ho. Tumne Kabhi socha hai ki inn all-time favorite myths ke peeche hidden messages hote hain?
Haan, bilkul! Kisi ek Dharm ki toh nahi, par universal truths hain inn myths mein jaise prem, samarpan, aur dharm parvash. Aur waise bhi, in myths ke liye humare culture aur traditions ka hona zaroori hai.
 Tum sahi keh rahi ho. Humare desh mein kitne saare dharm, jaati aur bhasha hai, lekin myths hum sabko jodte hain. Ek dusre ko samajhne ka upay hote hain.
Absolutely! Myths ke zariye hum apne ancestors ki teachings ko bhi follow kar paate hain. Pyar, nyay, aur samarpan ke jariye hum apne relationships mein bhi badlav lay sakte hain.
 Riya, tumhare thoughts sunke kuch alag sa feeling hoti hai. Tumhe knowledge aur sensitivity dono hai.
Rohan, shukriya! Waise, kya tumhe koi myth ya folklore pata hai jo love story ke upar ho?
 Haan, hai! Mirza-Sahiban! Unki pyari si kahani aur unki mohabbat ko vishwas karne ki himmat, dil se jude logon ko inspire karti hai. Tumhe unki kahani ke baare mein pata hai?
Haan, suna hai! Woh dono ek doosre se itne pagal the ki unki prem kahaniyan ab bhi logon ko bewakoof banane ka kaam karti hai. Itni saari prem kahaniyon mein se woh ek mera favorite hai.
 Sach hai, yehi toh woh powers hain jo folklore aur myths mein hai! Woh humare zindagi mein ek pyaara sa magical touch laate hain.
Aur woh magical touch hi toh hume ek doosre ke kareeb le aata hai, hai na?
 Haan, bilkul! Yeh myths aur folklore hamare beech woh chemistry banate hain jo hum zara sa flirting tak le ja sakte hain.
Achha toh, tum flirting kar rahe ho mujhse, Mr. Rohan?
 Haan, Riya! Tumhare saath time spend karte karte, I can't help but fall for you, aur mythology ki baat karke toh woh feeling aur bhi gehri ho gayi hai.
Wow, Rohan! Tum toh romantic merge karte ja rahe ho! Par, mujhe bhi lagta hai, ki humara connection kuch khaas hai.
 Hey, Riya! Tumne kabhi Indian folklore aur myths ke baare mein suna hai?
Haan, mujhe toh yeh topics bohot pasand hai! Ramayana aur Mahabharata jaise kisse mere dil ko chhoo jate hain. Tumhare paas koi favorite myth ya folklore hai?
 Haan, mere liye Krishna aur Radha ka prem katha sabse pyara hai! Unki pyari si raas leela aur bansuri ki dhun dil ko choo leti hai. Tum batao koi myth jo tumko bahut pasand hai?
Oh, mujhe Shiv aur Parvati ki paa raha hai! Unki prem kahani aur Ganga maiya se girti hui Ganga ka roop mere mann ko sukoon deta hai.
 Wah, Riya! Tum bahut deep thoughts rakhti ho. Tumne Kabhi socha hai ki inn all-time favorite myths ke peeche hidden messages hote hain?
Haan, bilkul! Kisi ek Dharm ki toh nahi, par universal truths hain inn myths mein jaise prem, samarpan, aur dharm parvash. Aur waise bhi, in myths ke liye humare culture aur traditions ka hona zaroori hai.
 Tum sahi keh rahi ho. Humare desh mein kitne saare dharm, jaati aur bhasha hai, lekin myths hum sabko jodte hain. Ek dusre ko samajhne ka upay hote hain.
Absolutely! Myths ke zariye hum apne ancestors ki teachings ko bhi follow kar paate hain. Pyar, nyay, aur samarpan ke jariye hum apne relationships mein bhi badlav lay sakte hain.
 Riya, tumhare thoughts sunke kuch alag sa feeling hoti hai. Tumhe knowledge aur sensitivity dono hai.
Rohan, shukriya! Waise, kya tumhe koi myth ya folklore pata hai jo love story ke upar ho?
 Haan, hai! Mirza-Sahiban! Unki pyari si kahani aur unki mohabbat ko vishwas karne ki himmat, dil se jude logon ko inspire karti hai. Tumhe unki kahani ke baare mein pata hai?
Haan, suna hai! Woh dono ek doosre se itne pagal the ki unki prem kahaniyan ab bhi logon ko bewakoof banane ka kaam karti hai. Itni saari prem kahaniyon mein se woh ek mera favorite hai.
 Sach hai, yehi toh woh powers hain jo folklore aur myths mein hai! Woh humare zindagi mein ek pyaara sa magical touch laate hain.
Aur woh magical touch hi toh hume ek doosre ke kareeb le aata hai, hai na?
 Haan, bilkul! Yeh myths aur folklore hamare beech woh chemistry banate hain jo hum zara sa flirting tak le ja sakte hain.
Achha toh, tum flirting kar rahe ho mujhse, Mr. Rohan?
 Haan, Riya! Tumhare saath time spend karte karte, I can't help but fall for you, aur mythology ki baat karke toh woh feeling aur bhi gehri ho gayi hai.
Wow, Rohan! Tum toh romantic merge karte ja rahe ho! Par, mujhe bhi lagta hai, ki humara connection kuch khaas hai."""

import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer()

tokenizer.fit_on_texts([text])

total_unique_words = len(tokenizer.word_index)
print(total_unique_words)

max(tokenizer.word_counts, key=tokenizer.word_counts.get)

input_sequence = []
for sentences in text.split('\n'):
  tokenized_sentence = tokenizer.texts_to_sequences([sentences])[0]
  for i in range(1,len(tokenized_sentence)):
    input_sequence.append(tokenized_sentence[:i+1])

max_len = max(len(x)for x in input_sequence) #gives the max words in a sentence
print(max_len)

from tensorflow.keras.preprocessing.sequence import pad_sequences

padded_input_sequence = pad_sequences(input_sequence,maxlen = max_len,padding='pre')
padded_input_sequence.shape

x = padded_input_sequence[ : , :-1] # syntax [from_row : till_row, from_column : till column]

y = padded_input_sequence[ : , -1]

from tensorflow.keras.utils import to_categorical
y = to_categorical(y, num_classes = total_unique_words+1) # one hot encoding the y, OHE has a extra 0 at the start therefore 364 not 363
y.shape

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

model = Sequential()
model.add(Embedding(total_unique_words+1,100,input_length = x.shape[1])) # making embeddings of x
model.add(LSTM(150))
model.add(Dense(total_unique_words+1,activation='softmax'))

model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(x,y,epochs = 100)

import numpy as np

test = "aut"

for i in range(1):
  token_text = tokenizer.texts_to_sequences([test])
      #padding
  padded_text = pad_sequences(token_text,maxlen = max_len,padding='pre')
      #predict
  position = np.argmax(model.predict(padded_text))

  for word,index in tokenizer.word_index.items():
    if index == position:
      test = test + " " + word
print(test)

model.save("model.h5")